/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = [''];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRjovbWFuaXNoL29tbmktbGF3LXByb2plY3QvcGFja2FnZS0yL3NyYy9zZWN0aW9uLWJvYXJkLXZpZXcvc2VjdGlvbi1ib2FyZC12aWV3LmNvbXBvbmVudC5jc3Muc2hpbS5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRjovbWFuaXNoL29tbmktbGF3LXByb2plY3QvcGFja2FnZS0yL3NyYy9zZWN0aW9uLWJvYXJkLXZpZXcvc2VjdGlvbi1ib2FyZC12aWV3LmNvbXBvbmVudC5jc3MiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
