/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './section-board-view.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '@angular/router';
import * as i3 from './section-board-view.component';
const styles_SectionBoardViewComponent:any[] = [i0.styles];
export const RenderType_SectionBoardViewComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_SectionBoardViewComponent,data:{}});
export function View_SectionBoardViewComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'h1',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted(-1,(null as any),['\n  section-board-view works!\n'])),(_l()(),i1.ɵted(-1,
      (null as any),['\n'])),(_l()(),i1.ɵeld(3,16777216,(null as any),(null as any),
      1,'router-outlet',([] as any[]),(null as any),(null as any),(null as any),(null as any),
      (null as any))),i1.ɵdid(4,212992,(null as any),0,i2.RouterOutlet,[i2.ChildrenOutletContexts,
      i1.ViewContainerRef,i1.ComponentFactoryResolver,[8,(null as any)],i1.ChangeDetectorRef],
      (null as any),(null as any))],(_ck,_v) => {
    _ck(_v,4,0);
  },(null as any));
}
export function View_SectionBoardViewComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'app-section-board-view',
      ([] as any[]),(null as any),(null as any),(null as any),View_SectionBoardViewComponent_0,
      RenderType_SectionBoardViewComponent)),i1.ɵdid(1,114688,(null as any),0,i3.SectionBoardViewComponent,
      ([] as any[]),(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const SectionBoardViewComponentNgFactory:i1.ComponentFactory<i3.SectionBoardViewComponent> = i1.ɵccf('app-section-board-view',
    i3.SectionBoardViewComponent,View_SectionBoardViewComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRjovbWFuaXNoL29tbmktbGF3LXByb2plY3QvcGFja2FnZS0yL3NyYy9zZWN0aW9uLWJvYXJkLXZpZXcvc2VjdGlvbi1ib2FyZC12aWV3LmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9GOi9tYW5pc2gvb21uaS1sYXctcHJvamVjdC9wYWNrYWdlLTIvc3JjL3NlY3Rpb24tYm9hcmQtdmlldy9zZWN0aW9uLWJvYXJkLXZpZXcuY29tcG9uZW50LnRzIiwibmc6Ly8vRjovbWFuaXNoL29tbmktbGF3LXByb2plY3QvcGFja2FnZS0yL3NyYy9zZWN0aW9uLWJvYXJkLXZpZXcvc2VjdGlvbi1ib2FyZC12aWV3LmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRjovbWFuaXNoL29tbmktbGF3LXByb2plY3QvcGFja2FnZS0yL3NyYy9zZWN0aW9uLWJvYXJkLXZpZXcvc2VjdGlvbi1ib2FyZC12aWV3LmNvbXBvbmVudC50cy5TZWN0aW9uQm9hcmRWaWV3Q29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGgxPlxuICBzZWN0aW9uLWJvYXJkLXZpZXcgd29ya3MhXG48L2gxPlxuPHJvdXRlci1vdXRsZXQ+PC9yb3V0ZXItb3V0bGV0PiIsIjxhcHAtc2VjdGlvbi1ib2FyZC12aWV3PjwvYXBwLXNlY3Rpb24tYm9hcmQtdmlldz4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7O29CQ0FBO01BQUEsd0VBQUk7YUFBQSx3REFFQztNQUFBLHVCQUNMO01BQUE7TUFBQSx1QkFBQTtzREFBQTtNQUFBO0lBQUE7Ozs7b0JDSEE7TUFBQTswQ0FBQSxVQUFBO01BQUE7SUFBQTs7OzsifQ==
