/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = [''];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRjovbWFuaXNoL29tbmktbGF3LXByb2plY3QvcGFja2FnZS0yL3NyYy9zZWN0aW9uLWJvYXJkLXZpZXcvc2VjdGlvbi1ib2FyZC1jYXJkLXZpZXcvc2VjdGlvbi1ib2FyZC1jYXJkLXZpZXcuY29tcG9uZW50LmNzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9GOi9tYW5pc2gvb21uaS1sYXctcHJvamVjdC9wYWNrYWdlLTIvc3JjL3NlY3Rpb24tYm9hcmQtdmlldy9zZWN0aW9uLWJvYXJkLWNhcmQtdmlldy9zZWN0aW9uLWJvYXJkLWNhcmQtdmlldy5jb21wb25lbnQuY3NzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
