/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './section-board-card-view.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './section-board-card-view.component';
const styles_SectionBoardCardViewComponent:any[] = [i0.styles];
export const RenderType_SectionBoardCardViewComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_SectionBoardCardViewComponent,data:{}});
export function View_SectionBoardCardViewComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'p',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted(-1,(null as any),['\n  section-board-card-view works!\n'])),(_l()(),
      i1.ɵted(-1,(null as any),['\n']))],(null as any),(null as any));
}
export function View_SectionBoardCardViewComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'app-section-board-card-view',
      ([] as any[]),(null as any),(null as any),(null as any),View_SectionBoardCardViewComponent_0,
      RenderType_SectionBoardCardViewComponent)),i1.ɵdid(1,114688,(null as any),0,
      i2.SectionBoardCardViewComponent,([] as any[]),(null as any),(null as any))],
      (_ck,_v) => {
        _ck(_v,1,0);
      },(null as any));
}
export const SectionBoardCardViewComponentNgFactory:i1.ComponentFactory<i2.SectionBoardCardViewComponent> = i1.ɵccf('app-section-board-card-view',
    i2.SectionBoardCardViewComponent,View_SectionBoardCardViewComponent_Host_0,{},
    {},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRjovbWFuaXNoL29tbmktbGF3LXByb2plY3QvcGFja2FnZS0yL3NyYy9zZWN0aW9uLWJvYXJkLXZpZXcvc2VjdGlvbi1ib2FyZC1jYXJkLXZpZXcvc2VjdGlvbi1ib2FyZC1jYXJkLXZpZXcuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Y6L21hbmlzaC9vbW5pLWxhdy1wcm9qZWN0L3BhY2thZ2UtMi9zcmMvc2VjdGlvbi1ib2FyZC12aWV3L3NlY3Rpb24tYm9hcmQtY2FyZC12aWV3L3NlY3Rpb24tYm9hcmQtY2FyZC12aWV3LmNvbXBvbmVudC50cyIsIm5nOi8vL0Y6L21hbmlzaC9vbW5pLWxhdy1wcm9qZWN0L3BhY2thZ2UtMi9zcmMvc2VjdGlvbi1ib2FyZC12aWV3L3NlY3Rpb24tYm9hcmQtY2FyZC12aWV3L3NlY3Rpb24tYm9hcmQtY2FyZC12aWV3LmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRjovbWFuaXNoL29tbmktbGF3LXByb2plY3QvcGFja2FnZS0yL3NyYy9zZWN0aW9uLWJvYXJkLXZpZXcvc2VjdGlvbi1ib2FyZC1jYXJkLXZpZXcvc2VjdGlvbi1ib2FyZC1jYXJkLXZpZXcuY29tcG9uZW50LnRzLlNlY3Rpb25Cb2FyZENhcmRWaWV3Q29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPHA+XG4gIHNlY3Rpb24tYm9hcmQtY2FyZC12aWV3IHdvcmtzIVxuPC9wPlxuIiwiPGFwcC1zZWN0aW9uLWJvYXJkLWNhcmQtdmlldz48L2FwcC1zZWN0aW9uLWJvYXJkLWNhcmQtdmlldz4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQSx3RUFBRzthQUFBLDZEQUVDO2FBQUE7OztvQkNGSjtNQUFBOzhDQUFBLFVBQUE7dUNBQUE7O1FBQUE7Ozs7OyJ9
