/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './section-board-list-view.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './section-board-list-view.component';
const styles_SectionBoardListViewComponent:any[] = [i0.styles];
export const RenderType_SectionBoardListViewComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_SectionBoardListViewComponent,data:{}});
export function View_SectionBoardListViewComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'p',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted(-1,(null as any),['\n  section-board-list-view works!\n'])),(_l()(),
      i1.ɵted(-1,(null as any),['\n']))],(null as any),(null as any));
}
export function View_SectionBoardListViewComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'app-section-board-list-view',
      ([] as any[]),(null as any),(null as any),(null as any),View_SectionBoardListViewComponent_0,
      RenderType_SectionBoardListViewComponent)),i1.ɵdid(1,114688,(null as any),0,
      i2.SectionBoardListViewComponent,([] as any[]),(null as any),(null as any))],
      (_ck,_v) => {
        _ck(_v,1,0);
      },(null as any));
}
export const SectionBoardListViewComponentNgFactory:i1.ComponentFactory<i2.SectionBoardListViewComponent> = i1.ɵccf('app-section-board-list-view',
    i2.SectionBoardListViewComponent,View_SectionBoardListViewComponent_Host_0,{},
    {},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRjovbWFuaXNoL29tbmktbGF3LXByb2plY3QvcGFja2FnZS0yL3NyYy9zZWN0aW9uLWJvYXJkLXZpZXcvc2VjdGlvbi1ib2FyZC1saXN0LXZpZXcvc2VjdGlvbi1ib2FyZC1saXN0LXZpZXcuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Y6L21hbmlzaC9vbW5pLWxhdy1wcm9qZWN0L3BhY2thZ2UtMi9zcmMvc2VjdGlvbi1ib2FyZC12aWV3L3NlY3Rpb24tYm9hcmQtbGlzdC12aWV3L3NlY3Rpb24tYm9hcmQtbGlzdC12aWV3LmNvbXBvbmVudC50cyIsIm5nOi8vL0Y6L21hbmlzaC9vbW5pLWxhdy1wcm9qZWN0L3BhY2thZ2UtMi9zcmMvc2VjdGlvbi1ib2FyZC12aWV3L3NlY3Rpb24tYm9hcmQtbGlzdC12aWV3L3NlY3Rpb24tYm9hcmQtbGlzdC12aWV3LmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRjovbWFuaXNoL29tbmktbGF3LXByb2plY3QvcGFja2FnZS0yL3NyYy9zZWN0aW9uLWJvYXJkLXZpZXcvc2VjdGlvbi1ib2FyZC1saXN0LXZpZXcvc2VjdGlvbi1ib2FyZC1saXN0LXZpZXcuY29tcG9uZW50LnRzLlNlY3Rpb25Cb2FyZExpc3RWaWV3Q29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPHA+XG4gIHNlY3Rpb24tYm9hcmQtbGlzdC12aWV3IHdvcmtzIVxuPC9wPlxuIiwiPGFwcC1zZWN0aW9uLWJvYXJkLWxpc3Qtdmlldz48L2FwcC1zZWN0aW9uLWJvYXJkLWxpc3Qtdmlldz4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQSx3RUFBRzthQUFBLDZEQUVDO2FBQUE7OztvQkNGSjtNQUFBOzhDQUFBLFVBQUE7dUNBQUE7O1FBQUE7Ozs7OyJ9
