/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = [''];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRjovbWFuaXNoL29tbmktbGF3LXByb2plY3QvcGFja2FnZS0yL3NyYy9hZGQtc2VjdGlvbi1ib2FyZC9hZGQtc2VjdGlvbi1ib2FyZC5jb21wb25lbnQuY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Y6L21hbmlzaC9vbW5pLWxhdy1wcm9qZWN0L3BhY2thZ2UtMi9zcmMvYWRkLXNlY3Rpb24tYm9hcmQvYWRkLXNlY3Rpb24tYm9hcmQuY29tcG9uZW50LmNzcyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
