/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './section.module';
import * as i2 from './section.component.ngfactory';
import * as i3 from './add-section-board/add-section-board.component.ngfactory';
import * as i4 from './section-board-setup/section-board-setup.component.ngfactory';
import * as i5 from './section-board-view/section-board-view.component.ngfactory';
import * as i6 from './section-board-view/section-board-card-view/section-board-card-view.component.ngfactory';
import * as i7 from './section-board-view/section-board-list-view/section-board-list-view.component.ngfactory';
import * as i8 from '@angular/common';
import * as i9 from '@angular/router';
import * as i10 from './section-routing.module';
import * as i11 from './section.component';
import * as i12 from './add-section-board/add-section-board.component';
import * as i13 from './section-board-setup/section-board-setup.component';
import * as i14 from './section-board-view/section-board-view.component';
import * as i15 from './section-board-view/section-board-card-view/section-board-card-view.component';
import * as i16 from './section-board-view/section-board-list-view/section-board-list-view.component';
export const SectionModuleNgFactory:i0.NgModuleFactory<i1.SectionModule> = i0.ɵcmf(i1.SectionModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.SectionComponentNgFactory,i3.AddSectionBoardComponentNgFactory,i4.SectionBoardSetupComponentNgFactory,
              i5.SectionBoardViewComponentNgFactory,i6.SectionBoardCardViewComponentNgFactory,
              i7.SectionBoardListViewComponentNgFactory]],[3,i0.ComponentFactoryResolver],
              i0.NgModuleRef]),i0.ɵmpd(4608,i8.NgLocalization,i8.NgLocaleLocalization,
          [i0.LOCALE_ID]),i0.ɵmpd(512,i8.CommonModule,i8.CommonModule,([] as any[])),
          i0.ɵmpd(512,i9.RouterModule,i9.RouterModule,[[2,i9.ɵa],[2,i9.Router]]),i0.ɵmpd(512,
              i10.SectionRoutingModule,i10.SectionRoutingModule,([] as any[])),i0.ɵmpd(512,
              i1.SectionModule,i1.SectionModule,([] as any[])),i0.ɵmpd(1024,i9.ROUTES,
              () => {
                return [[{path:'',redirectTo:'/section/add',pathMatch:'full'},{path:'section',
                    component:i11.SectionComponent,children:[{path:'add',component:i12.AddSectionBoardComponent},
                        {path:'board-setup',component:i13.SectionBoardSetupComponent},
                        {path:'view',component:i14.SectionBoardViewComponent,children:[{path:'card-view',
                            component:i15.SectionBoardCardViewComponent},{path:'list-view',
                            component:i16.SectionBoardListViewComponent}]}]}]];
              },([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRjovbWFuaXNoL29tbmktbGF3LXByb2plY3QvcGFja2FnZS0yL3NyYy9zZWN0aW9uLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9GOi9tYW5pc2gvb21uaS1sYXctcHJvamVjdC9wYWNrYWdlLTIvc3JjL3NlY3Rpb24ubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
