/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './section-routing.module';
import * as i2 from './section.component.ngfactory';
import * as i3 from './add-section-board/add-section-board.component.ngfactory';
import * as i4 from './section-board-setup/section-board-setup.component.ngfactory';
import * as i5 from './section-board-view/section-board-view.component.ngfactory';
import * as i6 from './section-board-view/section-board-card-view/section-board-card-view.component.ngfactory';
import * as i7 from './section-board-view/section-board-list-view/section-board-list-view.component.ngfactory';
import * as i8 from '@angular/router';
import * as i9 from './section.component';
import * as i10 from './add-section-board/add-section-board.component';
import * as i11 from './section-board-setup/section-board-setup.component';
import * as i12 from './section-board-view/section-board-view.component';
import * as i13 from './section-board-view/section-board-card-view/section-board-card-view.component';
import * as i14 from './section-board-view/section-board-list-view/section-board-list-view.component';
export const SectionRoutingModuleNgFactory:i0.NgModuleFactory<i1.SectionRoutingModule> = i0.ɵcmf(i1.SectionRoutingModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.SectionComponentNgFactory,i3.AddSectionBoardComponentNgFactory,i4.SectionBoardSetupComponentNgFactory,
              i5.SectionBoardViewComponentNgFactory,i6.SectionBoardCardViewComponentNgFactory,
              i7.SectionBoardListViewComponentNgFactory]],[3,i0.ComponentFactoryResolver],
              i0.NgModuleRef]),i0.ɵmpd(512,i8.RouterModule,i8.RouterModule,[[2,i8.ɵa],
          [2,i8.Router]]),i0.ɵmpd(512,i1.SectionRoutingModule,i1.SectionRoutingModule,
          ([] as any[])),i0.ɵmpd(1024,i8.ROUTES,() => {
        return [[{path:'',redirectTo:'/section/add',pathMatch:'full'},{path:'section',
            component:i9.SectionComponent,children:[{path:'add',component:i10.AddSectionBoardComponent},
                {path:'board-setup',component:i11.SectionBoardSetupComponent},{path:'view',
                    component:i12.SectionBoardViewComponent,children:[{path:'card-view',
                        component:i13.SectionBoardCardViewComponent},{path:'list-view',
                        component:i14.SectionBoardListViewComponent}]}]}]];
      },([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRjovbWFuaXNoL29tbmktbGF3LXByb2plY3QvcGFja2FnZS0yL3NyYy9zZWN0aW9uLXJvdXRpbmcubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Y6L21hbmlzaC9vbW5pLWxhdy1wcm9qZWN0L3BhY2thZ2UtMi9zcmMvc2VjdGlvbi1yb3V0aW5nLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
