/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './section.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '@angular/router';
import * as i3 from './section.component';
const styles_SectionComponent:any[] = [i0.styles];
export const RenderType_SectionComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_SectionComponent,data:{}});
export function View_SectionComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵted(-1,(null as any),['\n'])),(_l()(),i1.ɵeld(1,0,
      (null as any),(null as any),4,'div',[['class','container-fluid main-base full-height']],
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted(-1,(null as any),['\n  '])),(_l()(),i1.ɵeld(3,16777216,(null as any),
      (null as any),1,'router-outlet',([] as any[]),(null as any),(null as any),(null as any),
      (null as any),(null as any))),i1.ɵdid(4,212992,(null as any),0,i2.RouterOutlet,
      [i2.ChildrenOutletContexts,i1.ViewContainerRef,i1.ComponentFactoryResolver,[8,
          (null as any)],i1.ChangeDetectorRef],(null as any),(null as any)),(_l()(),
      i1.ɵted(-1,(null as any),['\n'])),(_l()(),i1.ɵted(-1,(null as any),['\n\n'])),
      (_l()(),i1.ɵeld(7,0,(null as any),(null as any),7,'div',[['class','row']],(null as any),
          (null as any),(null as any),(null as any),(null as any))),(_l()(),i1.ɵted(-1,
          (null as any),['\n  '])),(_l()(),i1.ɵeld(9,0,(null as any),(null as any),
          4,'div',[['class','col-sm-8 col-sm-offset-2 text-center']],(null as any),
          (null as any),(null as any),(null as any),(null as any))),(_l()(),i1.ɵted(-1,
          (null as any),['\n    '])),(_l()(),i1.ɵeld(11,0,(null as any),(null as any),
          1,'div',[['class','toast']],(null as any),(null as any),(null as any),(null as any),
          (null as any))),(_l()(),i1.ɵted(-1,(null as any),['\n    '])),(_l()(),i1.ɵted(-1,
          (null as any),['\n  '])),(_l()(),i1.ɵted(-1,(null as any),['\n'])),(_l()(),
          i1.ɵted(-1,(null as any),['\n\n'])),(_l()(),i1.ɵeld(16,0,(null as any),(null as any),
          0,'div',[['class','loader']],(null as any),(null as any),(null as any),(null as any),
          (null as any))),(_l()(),i1.ɵted(-1,(null as any),['\n'])),(_l()(),i1.ɵeld(18,
          0,(null as any),(null as any),0,'div',[['class','overlay']],(null as any),
          (null as any),(null as any),(null as any),(null as any))),(_l()(),i1.ɵted(-1,
          (null as any),['\n\n']))],(_ck,_v) => {
    _ck(_v,4,0);
  },(null as any));
}
export function View_SectionComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'app-section',
      ([] as any[]),(null as any),(null as any),(null as any),View_SectionComponent_0,
      RenderType_SectionComponent)),i1.ɵdid(1,114688,(null as any),0,i3.SectionComponent,
      ([] as any[]),(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const SectionComponentNgFactory:i1.ComponentFactory<i3.SectionComponent> = i1.ɵccf('app-section',
    i3.SectionComponent,View_SectionComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRjovbWFuaXNoL29tbmktbGF3LXByb2plY3QvcGFja2FnZS0yL3NyYy9zZWN0aW9uLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9GOi9tYW5pc2gvb21uaS1sYXctcHJvamVjdC9wYWNrYWdlLTIvc3JjL3NlY3Rpb24uY29tcG9uZW50LnRzIiwibmc6Ly8vRjovbWFuaXNoL29tbmktbGF3LXByb2plY3QvcGFja2FnZS0yL3NyYy9zZWN0aW9uLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRjovbWFuaXNoL29tbmktbGF3LXByb2plY3QvcGFja2FnZS0yL3NyYy9zZWN0aW9uLmNvbXBvbmVudC50cy5TZWN0aW9uQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiXG48ZGl2IGNsYXNzPVwiY29udGFpbmVyLWZsdWlkIG1haW4tYmFzZSBmdWxsLWhlaWdodFwiPlxuICA8cm91dGVyLW91dGxldD48L3JvdXRlci1vdXRsZXQ+XG48L2Rpdj5cblxuPGRpdiBjbGFzcz1cInJvd1wiPlxuICA8ZGl2IGNsYXNzPVwiY29sLXNtLTggY29sLXNtLW9mZnNldC0yIHRleHQtY2VudGVyXCI+XG4gICAgPGRpdiBjbGFzcz1cInRvYXN0XCI+XG4gICAgPC9kaXY+XG4gIDwvZGl2PlxuPC9kaXY+XG5cbjxkaXYgY2xhc3M9XCJsb2FkZXJcIj48L2Rpdj5cbjxkaXYgY2xhc3M9XCJvdmVybGF5XCI+PC9kaXY+XG5cbiIsIjxhcHAtc2VjdGlvbj48L2FwcC1zZWN0aW9uPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDQUEsMENBQ0E7TUFBQTtNQUFBLHdFQUFtRDthQUFBLDZCQUNqRDtNQUFBO01BQUEscUNBQUE7TUFBQTtVQUFBLGtFQUErQjthQUFBLDJCQUMzQjtNQUVOO1VBQUEsMERBQWlCO1VBQUEseUJBQ2Y7VUFBQTtVQUFBLDBEQUFrRDtVQUFBLDJCQUNoRDtVQUFBO1VBQUEsZ0JBQW1CLDhDQUNiO1VBQUEseUJBQ0YsMENBQ0Y7aUJBQUEsNkJBRU47VUFBQTtVQUFBLGdCQUEwQiwwQ0FDMUI7VUFBQTtVQUFBLDBEQUEyQjtVQUFBO0lBWHpCOzs7O29CQ0ZGO01BQUE7aUNBQUEsVUFBQTtNQUFBO0lBQUE7Ozs7In0=
